### ISSUE TITLE
Update readme to be specific to the project

### ISSUE THREAD

**Issue by BrianGilbert** [druxt/demo-api.druxtjs.org#3]
**Is your feature request related to a problem? Please describe.**
The current readme doesn't fully explain the steps to get this up and running locally.

**Describe the solution you'd like**
Add steps to get a local instance fully configured ready for a Druxt frontend.

**Describe alternatives you've considered**
Maybe export config and commit instead?

**Additional context**

**Comment by Decipher** [comment]
Fixed.
